version: '3.8'

services:
  nestapp:
    build: ./
    container_name: nestapp
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgresdb1

  postgresdb1: 
    image: postgres:latest
    container_name: postgresdb1
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:

